name: AsyncAPI documents processing

on:
  push:
    branches:
      - feature/aysncapi-integration

permissions: write-all

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2

    #In case all defaults are fine for you, just add such step
    - name: Generating Markdown from my AsyncAPI document
      uses: docker://asyncapi/github-action-for-generator:2.1.22

    - name: Checking if stuff are available outside container
      run: echo "===" && ls && echo "===" && ls generated-html && echo "==="
      
    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: generated-html
