name: AsyncAPI documents processing

on:
  push:
    branches:
      - feature/aysncapi-integration

permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2
    - 
      name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    #Using another action for AsyncAPI for validation
    - name: Validating AsyncAPI document
      uses: WaleedAshraf/asyncapi-github-action@v0.0.10
      with:
        filepath: docs/api/my-asyncapi.yml

    #In case you do not want to use defaults, you for example want to use different template
    - name: Generating HTML from my AsyncAPI document
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          asyncapi/html-template:2.3.0 \
          -o /app/output.html \
          /docs/api/my-asyncapi.yml
    
    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: actions/upload-artifact@v2
      with:
        name: asyncapi-html
        path: output.html