name: AsyncAPI documents processing

on:
  push:
    branches:
      - feature/aysncapi-integration

permissions: write-all

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2

    #In case you do not want to use defaults, you for example want to use different template
    - name: Generating HTML from my AsyncAPI document
      uses: docker://asyncapi/github-action-for-generator:2.1.12
      with:
        template: '@asyncapi/html-template@0.28.4'
        filepath: docs/api/asyncapi.yml
        parameters: pdf=true baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
        output: generated-html

    - name: Checking if stuff are available outside container
      run: echo "===" && ls && echo "===" && ls generated-html && echo "==="

    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: generated-html
